### ISSUE TITLE
can't generate clean_data

### ISSUE THREAD

**Issue by HanwenWangBUPT** [mahaoxiang822/Scale-Balanced-Grasp#5]
I sincerely appreciate for your excellent work!

but I have some qestion,I can't generate clean_data,you apply code name "command_generate_clean_data.sh"  may be have some errors,
I change it to "python generate_clean_data.py --dataset_root data/mypath/graspnet --num_workers 40 --camera kinect",Although the program does not report an error, but there is no output.

![image](https://github.com/mahaoxiang822/Scale-Balanced-Grasp/assets/118330704/b2be4391-6e97-4ee2-8d86-3395e53582d4)

**Comment by huamo555** [comment]
I have encountered the same problem. Have you resolved it yet?

**Comment by huamo555** [comment]
> I sincerely appreciate for your excellent work!
> 
> but I have some qestion,I can't generate clean_data,you apply code name "command_generate_clean_data.sh" may be have some errors, I change it to "python generate_clean_data.py --dataset_root data/mypath/graspnet --num_workers 40 --camera kinect",Although the program does not report an error, but there is no output.
> 
> ![image](https://user-images.githubusercontent.com/118330704/262655948-b2be4391-6e97-4ee2-8d86-3395e53582d4.png)


I have encountered the same problem. Have you resolved it yet?

**Comment by HanwenWangBUPT** [comment]
Not yet,if you have any idea,please write in here,thanks

**Comment by mahaoxiang822** [comment]
Hello everyone, I apologize for the late reply as I have been occupied with other tasks. 
I have carefully checked the code for generating clean data and found that the issue was caused by a conflict between multiprocessing generation and the "compute_point_cloud_distance" from open3d. However, this issue does not occur in a single-threaded environment. I will correct this issue in the future. For now, you can use single-threaded generation as a workaround by modifying the end of dataset/generate_clean_data.py.
```
if __name__ == "__main__":
    dataset = GraspNetDataset(......)
    for i in tqdm(range(len(dataset))):
        dataset.save_data(i)
```

If you have any other questions, please contact here

**Comment by HanwenWangBUPT** [comment]
It's work,thanks
